Sputnik modify endpoint
Bioinformatics-internship-EPAM/plasmidEditor pull request #12
Opened 2022-05-16 17:09 UTC by itiszakk

2022-05-16 18:00 UTC, darina-ovis requested changes
Я не вижу endpoint-ов, которые используют эти методы

2022-05-16 18:04 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/editor/GenBankEditor.java
> +}
отличная идея использовать паттерт команда! 🔥

2022-05-20 18:00 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/controllers/GenBankEditorController.java
> +        return editor.add(request.getSubsequence(), request.getPosition(), request.getFileContent()).getSequenceAsString();
Хорошо бы валидировать содержимое request-а перед тем, как вставлять последовательность

2022-05-20 18:00 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/controllers/GenBankEditorController.java
> +            consumes = MediaType.APPLICATION_JSON_VALUE)
Насчет возвращаемых строк. Когда речь идет о API, обычно есть поддерживаемые форматы данных и как-то принято, что если приходит json, то json формат и возвращается. Вы можете ничего не возвращать, просто статус 201 в случае успеха

2022-05-21 14:11 UTC, Venjilin commented on src/main/java/com/plasmidEditor/sputnik/controllers/GenBankEditorController.java
> +        return editor.add(request.getSubsequence(), request.getPosition(), request.getFileContent()).getSequenceAsString();
Добавили. Но вставили проверку не в контроллер, а в сам эдитор.

2022-05-21 14:11 UTC, Venjilin commented on src/main/java/com/plasmidEditor/sputnik/controllers/GenBankEditorController.java
> +            consumes = MediaType.APPLICATION_JSON_VALUE)
Сделали

2022-05-24 11:58 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/editor/ModifyMethod.java
> +            (S sequence, int position, int offset) {}
можно было бы пустой метод сделать в абстрактном классе и где надо делать override. Но можете и так оставить

2022-05-24 11:58 UTC, darina-ovis commented on src/test/java/com/plasmidEditor/sputnik/GenBankEditorTests.java
> +            }
слишком много проверок для одного теста. лучше разбить на насколько маленьких тестов

2022-05-24 11:58 UTC, darina-ovis commented on src/test/java/com/plasmidEditor/sputnik/GenBankEditorTests.java
> +public class GenBankEditorTests {
все три теста очень похожи. старайтесь избегать дубликатов кода во всем коде, тесты - не исключение

2022-05-25 15:48 UTC, itiszakk commented on src/main/java/com/plasmidEditor/sputnik/editor/ModifyMethod.java
> +            (S sequence, int position, int offset) {}
Оставили так)

2022-05-25 15:48 UTC, itiszakk commented on src/test/java/com/plasmidEditor/sputnik/GenBankEditorTests.java
> +            }
Сделали

2022-05-25 15:49 UTC, itiszakk commented on src/test/java/com/plasmidEditor/sputnik/GenBankEditorTests.java
> +public class GenBankEditorTests {
Поправили

2022-05-26 09:59 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/controllers/GenBankEditorController.java
> +    public void addSequence(@RequestBody EditorParameters request) {
minor: обычно пост возращает что-то

2022-05-26 15:29 UTC, darina-ovis approved these changes

2022-05-26 15:29 UTC, merged