Add files via upload
Bioinformatics-internship-EPAM/plasmidEditor pull request #2
Opened 2022-04-20 06:33 UTC by Pelevina

2022-04-20 08:55 UTC, darina-ovis requested changes
Папки build не должно быть в репозитории.

2022-04-20 08:55 UTC, darina-ovis commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +@RestController
На этом этапе мы не создаем никаких endpoint-ов, контроллер не нужен.

2022-04-20 08:55 UTC, darina-ovis commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +	public void hello() {}
контроллер и application config как правило не находятся в одном классе. И сейчас нам не нужен контроллер

2022-04-20 09:55 UTC, Pelevina commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +@RestController
Без аннотации RestController выдаётся следующее сообщение на странице http://localhost:8080/:
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed Apr 20 12:51:48 MSK 2022
There was an unexpected error (type=Not Found, status=404).
Это нормально?

2022-04-20 10:11 UTC, Pelevina commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +	public void hello() {}
Начинка для приложения нужна?

2022-04-20 11:15 UTC, iporsh commented on demo/src/main/resources/application.properties
> +
Можно поменять название приложенния)

2022-04-20 11:18 UTC, iporsh commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +@RestController
Эта анатация нужна для того чтобы настроить spring , пометив этот класс как контроллер
так как в задаче это не требуется, тогда удали @RestController и @GetMapping("/")

2022-04-20 11:18 UTC, iporsh commented on demo/HELP.md
> +
Также стоит создать файл README

2022-04-20 11:20 UTC, iporsh commented on demo/src/main/resources/application.properties
> +
и настроить уровень логов

2022-04-20 11:23 UTC, iporsh commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +public class DemoApplication {
Так же не уверен, что это хорошее имя для приложение )))) у вас есть название ракета или спутник ))) демо как-то не очень)

2022-04-20 11:26 UTC, iporsh commented on demo/build.gradle
> +	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
Какую версию джавы вы используете?

2022-04-20 12:07 UTC, iporsh commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +	public void hello() {}
Думаю пока это не требуется

2022-04-20 15:42 UTC, darina-ovis commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +@RestController
> Без аннотации RestController выдаётся следующее сообщение на странице http://localhost:8080/: Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback. Wed Apr 20 12:51:48 MSK 2022 There was an unexpected error (type=Not Found, status=404). Это нормально?

Да, это нормально. Так как у нашего приложения нет еще контроллеров на этом этапе.

2022-04-20 17:08 UTC, Pelevina commented on demo/build.gradle
> +	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
11

2022-04-20 17:16 UTC, Pelevina commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +public class DemoApplication {
Переименовано в sputnik

2022-04-20 17:28 UTC, Pelevina commented on demo/HELP.md
> +
Readme создан

2022-04-20 18:18 UTC, Pelevina commented on demo/src/main/java/com/example/demo/DemoApplication.java
> +@RestController
аннотации @RestController и @GetMapping с объявлением метода hello удалены

2022-04-20 18:23 UTC, Pelevina commented on demo/src/main/resources/application.properties
> +
Что конкретно нужно настроить?

2022-04-20 19:13 UTC, Pelevina commented on demo/src/main/resources/application.properties
> +
Что и где нужно логировать?

2022-04-21 07:42 UTC, iporsh commented on demo/src/main/resources/application.properties
> +
добавьте хотя бы одну настройку, чтобы понять что пропертиес файл работает

2022-04-21 08:41 UTC, iporsh commented on sputnik/src/main/java/com/example/sputnik/Sputnik.java
> +public class Sputnik {
SputnikApplication лучше, так как Sputnik - это выглядит как класс - объект

2022-04-21 08:44 UTC, iporsh commented on sputnik/src/main/resources/sputnik.properties
> +logging.level.org.apache.zookeeper=WARN
а для чего это свойство?

2022-04-21 08:44 UTC, iporsh commented on sputnik/readme.md
> +This is Spring Boot skeleton
обычно это имя файла пишится большими буквами + стоит в него хоть что-то добавить по существу
например:
как запустить приложение
список команды

2022-04-21 09:04 UTC, Pelevina commented on demo/src/main/resources/application.properties
> +
Имя файла поменялось и добавлены уровни журналирования

2022-04-21 09:35 UTC, Pelevina commented on sputnik/src/main/resources/sputnik.properties
> +logging.level.org.apache.zookeeper=WARN
Эти свойства убрать? Какие свойства нужны приложению?

2022-04-21 09:38 UTC, Pelevina commented on sputnik/src/main/java/com/example/sputnik/Sputnik.java
> +public class Sputnik {
Переименовано в SputnikApplication

2022-04-21 09:40 UTC, iporsh commented on sputnik/src/main/resources/sputnik.properties
> +logging.level.org.apache.zookeeper=WARN
тут вопрос к тебе, что ты делаешь настройками?
Ты должна сама понять, что нужно

2022-04-21 09:56 UTC, Pelevina commented on sputnik/readme.md
> +This is Spring Boot skeleton
Добавила, как запустить приложение.

2022-04-21 10:02 UTC, Pelevina commented on sputnik/src/main/resources/sputnik.properties
> +logging.level.org.apache.zookeeper=WARN
Эти свойство удалены.

2022-04-21 10:02 UTC, iporsh commented on sputnik/src/main/resources/sputnik.properties
> +
Я думаю проперти, которые ты сюда добавишь не будут работать в спринге!

2022-04-21 11:27 UTC, Pelevina commented on sputnik/src/main/resources/sputnik.properties
> +
Если сменить название на дефолтное application.properties, будут ли проперти в нём работать?

2022-04-21 11:33 UTC, darina-ovis approved these changes

2022-04-21 11:58 UTC, Pelevina commented on sputnik/src/main/resources/sputnik.properties
> +
Конфигурационные классы нужны на этом этапе?

2022-04-21 14:02 UTC, suhova commented on sputnik/src/main/resources/sputnik.properties
> +
В SputnikApplicationTests пруф, что проперти с именем из application.properties подтягиваются

2022-04-21 15:33 UTC, merged