Added postgres database
Bioinformatics-internship-EPAM/plasmidEditor pull request #4
Opened 2022-04-21 19:59 UTC by DmitryVarlamov

2022-04-21 20:10 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/postgres/GenBankTable.java
> +public class GenBankTable {
GenBankTable  - это плохое название , разве это таблица? Это одна запись в базе
Обычно пишут что-то вроде GenBankEnity

2022-04-21 20:10 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/postgres/GenBankTable.java
> +package com.plasmideditor.rocket.postgres;
имя пакета не очень хорошее, т.к. он не передает суть
в данном случае ,  думаю правильней entities

2022-04-21 20:10 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/repos/Repository.java
> +package com.plasmideditor.rocket.repos;
лучше называть полным именем  repositories

2022-04-21 20:10 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/repos/Repository.java
> +public interface Repository extends JpaRepository<GenBankTable, Long> {
Repository название класса ничего не обозначает, и если у тебя появится новая база таблица и новый репозиторий, то нельзя будет понять по имени класса к чему это относится
стоит переименовать

2022-04-21 20:10 UTC, iporsh commented on src/main/resources/application.properties
> +server.port=9090
зачем такой странный порт?

2022-04-21 20:10 UTC, iporsh commented on src/main/resources/application.properties
> +spring.jpa.generate-ddl=true
что-то я не увидел flyway и скрипты к нему

2022-04-21 20:13 UTC, iporsh commented on Dockerfile
> +FROM postgres:14
стоит добавить в README как это инициализировать

2022-04-21 20:14 UTC, DmitryVarlamov commented on src/main/resources/application.properties
> +spring.jpa.generate-ddl=true
А можно пожалуйста поподробнее объяснить, зачем и как он тут должен использоваться?

2022-04-21 20:15 UTC, DmitryVarlamov commented on Dockerfile
> +FROM postgres:14
Вы имеете в виду запуск вручную через docker build + docker run?
Мы просто в gradle.build добавили создание докер образа и его запуск

2022-04-21 20:19 UTC, iporsh commented on Dockerfile
> +FROM postgres:14
да, я про вручную

2022-04-21 20:22 UTC, iporsh commented on src/main/resources/application.properties
> +spring.jpa.generate-ddl=true
Дело в том, что у тебя нет схемы базы данных
ты это ручками локально сделал, и теперь никто не может этим воспользоваться
ты должен сделать скрипт создания схемы базы данных и создать таблицу (для твоей энтити)
посмотри в сторону flyway
+ сделать тесты, на CRUD в базу данных

2022-04-21 20:25 UTC, iporsh commented on Dockerfile
> +FROM postgres:14
и можно на ТЫ)))

2022-04-21 20:26 UTC, DmitryVarlamov commented on Dockerfile
> +FROM postgres:14
Не заметил комментарий, на всякий случай уже оба способа указал :)

2022-04-21 20:39 UTC, DmitryVarlamov commented on src/main/resources/application.properties
> +spring.jpa.generate-ddl=true
А подойдет ли такое решение:
Сделать SQL скрипт, который будет сетапить БД с уже готовой схемой и добавить его в Dockerfile.
Для этого всего 1 строчку нужно будет в Dockerfile дописать
COPY psql_dump.sql /docker-entrypoint-initdb.d/

Ну и сам sql скрипт тоже :)

2022-04-22 08:28 UTC, iporsh commented on src/main/resources/application.properties
> +spring.jpa.generate-ddl=true
не, так лучше не делать... это как - то  через одно место)
для этого есть так называемая технология МИГРАЦИЯ

2022-04-22 08:44 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/postgres/GenBankTable.java
> +public class GenBankTable {
done.

2022-04-22 08:53 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/postgres/GenBankTable.java
> +package com.plasmideditor.rocket.postgres;
done.

2022-04-22 08:53 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/repos/Repository.java
> +package com.plasmideditor.rocket.repos;
done.

2022-04-22 08:53 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/repos/Repository.java
> +public interface Repository extends JpaRepository<GenBankTable, Long> {
Done.

2022-04-22 09:54 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +
Хотел бы здесь добавить, что а где ID у таблицы?

2022-04-22 09:55 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    private String firstName;
Я не уверен, что у тебя получилось записать хоть что-то в базу) а точнее взять из базы

2022-04-22 14:36 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    private String firstName;
Упс, firstName остался с чернового варианта, поправлю. Консёрн только в этом был или в чём-то ещё?

2022-04-26 15:08 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    private String firstName;
firstName изменил на version

2022-04-27 15:27 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +
done.

2022-04-28 17:36 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    private Long genbank_id;
camelCase для переменных

2022-04-28 17:40 UTC, darina-ovis requested changes
Не вижу ограничений на уникальность accession + version

2022-04-29 14:06 UTC, DmitryVarlamov commented on src/main/resources/application.properties
> +spring.jpa.generate-ddl=true
Понял, сделаем через goose
https://github.com/pressly/goose

2022-04-29 14:07 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    private Long genbank_id;
done.

2022-04-29 14:10 UTC, DmitryVarlamov commented
Ограничение на уникальность accession + version будет в самой схеме БД, внутри миграции

2022-05-03 11:26 UTC, DmitryVarlamov commented on src/main/resources/application.properties
> +server.port=9090
заменили на 8080

2022-05-03 11:31 UTC, DmitryVarlamov commented
Мы зарезолвили конфликт

2022-05-04 07:49 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    public void setGenbankId(Long genbankId) {
лучше использовать lombok
тогда тупо эти методы не нужну будут

2022-05-04 07:50 UTC, iporsh commented on src/main/resources/db/migration/001_init_migration.sql
> +-- +goose Up
тебе нужно добавить отдельную схему, грузить все в public не очень хорошее решение

2022-05-04 09:03 UTC, DmitryVarlamov commented on src/main/resources/db/migration/001_init_migration.sql
> +-- +goose Up
Добавил создание схемы genbank и ее удаление при отмене миграции

2022-05-04 10:15 UTC, iporsh commented on src/main/resources/db/migration/001_init_migration.sql
> +SELECT 'down SQL query';
не уверен, что эта часть вообще нужна

2022-05-04 10:20 UTC, DmitryVarlamov commented on src/main/resources/db/migration/001_init_migration.sql
> +SELECT 'down SQL query';
Все миграции в goose содержат 2 части: up query и down query
Начальная миграция не исключение.
наличие down query помогает откатывать миграции с помощью команд goose down и goose down-to

2022-05-04 15:45 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    public void setGenbankId(Long genbankId) {
Добавил использование lombok

2022-05-06 08:19 UTC, iporsh commented on src/main/resources/db/migration/001_init_migration.sql
> +DROP SCHEMA genbank;
А где вообще тесты?

2022-05-06 20:16 UTC, EvgeniyGeraskin commented on src/main/resources/db/migration/001_init_migration.sql
> +DROP SCHEMA genbank;
Добавил.

2022-05-11 11:27 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/GenBankData.java
> +@AllArgsConstructor
не все из этих конструкторов нужны) удали лишние

2022-05-11 11:28 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +        uniqueConstraints = {@UniqueConstraint(columnNames = {"accession", "version"})}
`uniqueConstraints = {@UniqueConstraint(columnNames = {"accession", "version"}`

не надо это делать на уровне энтити, при развитии поддерживать и в схеме базы  и в энтите будет требовать больше усилий (представь , что таких сущьностей около 100 и поэтому помнить, что где и в какой энтити  плодят только ошибки)

2022-05-11 11:32 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/PostgresTestContainer.java
> +            .withDatabaseName("plasmid_database_test")
а зачем это новая сущьность (plasmid_database_test)? почему в тестах нельзя использовать тоже самое , что в боевой базе?

2022-05-11 11:32 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/PostgresTestContainer.java
> +            TestPropertyValues.of(
опять же зачем это все?

2022-05-11 11:35 UTC, iporsh commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/plasmid_database_test
не надо делать отличную базу. 
В твоем случае тебе надо поднять тестконтейнерс с постгрей, после чего выцепать из контрейнера  свойства(пароль и имя, и т.д) и пробросить в спринг, в таком случае у тебя тесты будут полностью изолированы, скачают туже схему  (которую ты создал и накатил в этот тестовый контейнер) и могут норм работать

2022-05-11 11:37 UTC, iporsh commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/plasmid_database_test
`    @Bean
    public PostgreSQLContainer postgreSQLContainer() {
        final PostgreSQLContainer postgreSQLContainer = new PostgreSQLContainer("postgres:11.8");
        postgreSQLContainer.start();
        return postgreSQLContainer;
    }

    @Bean
    public DataSource datasource(PostgreSQLContainer postgreSQLContainer) {
        return DataSourceBuilder.create()
                .driverClassName(postgreSQLContainer.getDriverClassName())
                .url(postgreSQLContainer.getJdbcUrl())
                .username(postgreSQLContainer.getUsername())
                .password(postgreSQLContainer.getPassword())
                .build();
    }`

2022-05-11 16:13 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/GenBankData.java
> +@AllArgsConstructor
done.

2022-05-11 16:14 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +        uniqueConstraints = {@UniqueConstraint(columnNames = {"accession", "version"})}
done.

2022-05-11 16:44 UTC, DmitryVarlamov commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +        uniqueConstraints = {@UniqueConstraint(columnNames = {"accession", "version"})}
Ограничение стоит теперь только на уровне базы данных
https://github.com/Bioinformatics-internship-EPAM/plasmidEditor/pull/4/files#diff-0885f2b26015fa640d0517075bec8860268210068b38f70fbf51779a30061763R7

2022-05-11 17:00 UTC, EvgeniyGeraskin commented on src/test/java/com/plasmideditor/rocket/PostgresTestContainer.java
> +            .withDatabaseName("plasmid_database_test")
done.

2022-05-11 17:01 UTC, EvgeniyGeraskin commented on src/test/java/com/plasmideditor/rocket/PostgresTestContainer.java
> +            TestPropertyValues.of(
done.

2022-05-11 17:01 UTC, EvgeniyGeraskin commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/plasmid_database_test
Не знаю правильно ли я всё понял, но изменения внёс. Можно смотреть.

2022-05-12 10:27 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    final private ModelMapper mapper = new ModelMapper();
Обычно Маппер делает отдельным классом GenBankMapper и он extends ModelMapper

2022-05-12 15:28 UTC, darina-ovis approved these changes

2022-05-13 11:23 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    final private ModelMapper mapper = new ModelMapper();
done.

2022-05-13 11:25 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    @Autowired
@Autowired как ты думаешь это нужно?)))

2022-05-13 11:26 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    private final GenBankRepository repository;
`private final`
и `final private`
выбери что-то одно)

2022-05-13 11:30 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    @Autowired
Здесь наверно всё же не нужно

2022-05-13 11:31 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    private final GenBankRepository repository;
done.

2022-05-13 11:31 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    @Autowired
done.

2022-05-13 11:51 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/GenBankServiceTests.java
> +    @Autowired
@Autowired это нужно?

2022-05-13 11:53 UTC, EvgeniyGeraskin commented on src/test/java/com/plasmideditor/rocket/GenBankServiceTests.java
> +    @Autowired
done.

2022-05-13 11:56 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/GenBankServiceTests.java
> +    void uploadTest() {
Из бест практики, тесты должны быть изолированны. 
что под этим подразумевается:
- тест должен сам генерировать все для себя
- тесты должны делать только ограниченное количество assert
Для чего это все нужно:
- чтобы тесты могли выполняться параллельно
- чтобы после прогона всех тестов в отчете фигурировали все проблемы, а не первый попавшийся затык
`        assertNotNull(uploadObj1);
        assertEquals(uploadObj1.getAccession(), "test_accession");
        assertEquals(uploadObj1.getVersion(), "test_version");
        assertEquals(uploadObj1.getFile(), "test_file");

        assertNotNull(uploadObj2);
        assertEquals(uploadObj2.getAccession(), "test_accession_2");
        assertEquals(uploadObj2.getVersion(), "test_version_2");
        assertEquals(uploadObj2.getFile(), "test_file_2");`
посмотри сколько у тебя их...
если у тебя все упадет на assertNotNull(uploadObj1) (первый ассерт)
то тогда ты не поймешь кикие из следующих у тебя не работает

2022-05-13 14:29 UTC, EvgeniyGeraskin commented on src/test/java/com/plasmideditor/rocket/GenBankServiceTests.java
> +    void uploadTest() {
Ну если упадёт на первом ассерте, то остальные и проверять нет смысла, так как значение uploadObj1 будет Null. А вот если не Null, то уже смотрим, что там конкретно лежит.

Мне казалось это логичным.

Если такой подход не верный, то как сделать так, чтобы соответствовало критериям "хорошего теста"?

2022-05-16 11:05 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/GenBankServiceTests.java
> +    void uploadTest() {
Для меня критично, что сделан ордеринг и данные грузяться в начале. Тесты должны быть изолированы иначе потом их сложно поддерживать

2022-05-16 11:10 UTC, iporsh commented on src/main/resources/application.properties
> +server.port=9090
лучше 80)

2022-05-16 11:11 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    private String firstName;
переменную тоже стоит  переименовать

2022-05-16 11:14 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +        schema = "genbank",
это можно перетащить в константу, чтобы потом нормально использовать и в других энтити

2022-05-16 16:35 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +    private String firstName;
Так это уже было сделано (outdated написано). В свежих изменениях всё в порядке с именами :)

2022-05-16 17:26 UTC, EvgeniyGeraskin commented on src/test/java/com/plasmideditor/rocket/GenBankServiceTests.java
> +    void uploadTest() {
Добавил setUp и tearDown и убрал ордеринг. Теперь тесты независимы.

2022-05-16 17:26 UTC, EvgeniyGeraskin commented on src/main/resources/application.properties
> +server.port=9090
done.

2022-05-16 17:33 UTC, EvgeniyGeraskin commented on src/main/java/com/plasmideditor/rocket/entities/GenBankEntity.java
> +        schema = "genbank",
done.

2022-05-16 21:16 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    public GenBankData get(Long id){
в названия тоже луше использовать genBankId
пройдись по всему  коду и попровь плиз

2022-05-17 07:35 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/services/GenBankService.java
> +    public GenBankData get(Long id){
Long id -> genBankId

2022-05-17 07:36 UTC, merged