Sputnik - Add ability to read/write Genbank files
Bioinformatics-internship-EPAM/plasmidEditor pull request #5
Opened 2022-04-22 12:46 UTC by ZhukovaKsenia

2022-04-22 13:24 UTC, iporsh commented on src/test/java/com/plasmidEditor/sputnik/GenbankManagerTests.java
> +    private static String readStringFromFile(String path) {
предлагаю вынести специальные методы в отдельные классы

2022-04-22 13:25 UTC, iporsh commented on src/test/java/com/plasmidEditor/sputnik/GenbankManagerTests.java
> +    private void checkFeaturesNP_000257(ProteinSequence proteinSequence) {
я  думаю, что вам  надо вытащить все в интерфейс и в его реализацию

2022-04-22 13:25 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/GenbankManager.java
> +    public DNASequence readDNAByURL(String accession) {
я думаю, что вам надо вытащить все в интерфейс и в его реализацию

2022-04-22 13:26 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/GenbankManager.java
> +    public DNASequence readDNAByURL(String accession) {
Тебе надо подумать, над использованием какое-нибудь паттерна

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +            System.err.println("Unable to get Genbank file with accession " + accession + " by URL");
стоит сделать свою отдельную ошибку

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +            LinkedHashMap<String, DNASequence> dnaSequences =
LinkedHashMap это реализация, а нужно интерфейс

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +        File dnaFile = new File(path);
что случится если path == null?

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +            return dnaSequences.entrySet().iterator().next().getValue();
чесно говоря  - это не читаемый код... что он делает и для чего не понятно...

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +            e.printStackTrace();
добавь отдельную ошибку

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +        FileOutputStream out = null;
плохой код посмотри в сорону конструкции try(new FileOutputStream(fileName))

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +        try {
зачем отделный трай?

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +            e.printStackTrace();
не читаемо, так как совсем не понятно зачем все выводить в консоль

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/ProteinGenbankManager.java
> +            System.err.println("Unable to get Genbank file with accession " + accession + " by URL");
смотри выше или ниже про отдельную ошибку и вывод

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/ProteinGenbankManager.java
> +        return null;
вообще это номальный кейс, когда null?

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/ProteinGenbankManager.java
> +        File protFile = new File(path);
что будет если path ==null?

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/ProteinGenbankManager.java
> +            LinkedHashMap<String, ProteinSequence> protSequences =
используй интерфейс , а не реализацию

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/ProteinGenbankManager.java
> +            System.err.println("Unable to read data from file " + path);
смотри выши или ниже об этом

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/ProteinGenbankManager.java
> +        return null;
это корректый кейс?

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/ProteinGenbankManager.java
> +        try {
очень много траев , посмотри мои коментарии про это выше или ниже

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/ProteinGenbankManager.java
> +            System.err.println("Unable to find file " + fileName);
и про ошибки тоже

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReaderUtils.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
прикольно))) разные варианты использования) постарайся одинаково писать, тогда это легче  читать

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReaderUtils.java
> +            e.printStackTrace();
читай выше

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReaderUtils.java
> +        return "";
это корректно?

2022-04-25 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReaderUtils.java
> +            String line = br.readLine();
тут выглядит некрасиво
стоит в ифе проверять, что если есть следующая строчка, тогда что-то делать

2022-04-25 12:11 UTC, suhova commented on src/main/java/com/plasmidEditor/sputnik/utils/ReaderUtils.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
Что есть разные варианты использования?

2022-04-25 12:18 UTC, darina-ovis requested changes
Посмотрите еще разок на интерфейс GenbankManager на предмет того, действительно ли 2 метода на чтение - это разная логика. А также в обеих реализациях много повторений кода - посмотрите, можно ли от этого избавиться и унифицировать код?

2022-04-25 12:18 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +        return null;
не очень удачное решение глотать ошибку и возвращать null. Тот, кто будет пользоваться этим методом, должен будет делать проверку на null и смысл null в данном случае - это что-то пошло не так, но узнать что, невозможно, так как ошибка проглочена. В итоге мы увидим где-нибудь NPE и будем гадать почему. Когда читается некорректный файл, метод должен об этом явно говорить. Бросать ошибку, так как дальнейшая работа невозможна. Null маскирует ошибку, что неправильно

2022-04-25 12:18 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/DNAGenbankManager.java
> +            e.printStackTrace();
используйте log-и, вы же их добавили в зависимость)

2022-04-25 12:18 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/GenbankManager.java
> +    public T readFromFile(String path);
мне кажется, что тут проблема на уровне интерфейса с чтением. Локально мы читаем или удаленно - это детали реализации и на уровне интерфейса лучше принимать просто url (file или http) и дальше иметь 2 реализации.

2022-04-25 12:18 UTC, darina-ovis commented on src/test/java/com/plasmidEditor/sputnik/GenbankManagerTests.java
> +    }
По факту, это тест на корректность работы biojava, а не вашего метода.

2022-04-25 12:18 UTC, darina-ovis commented on src/test/java/com/plasmidEditor/sputnik/GenbankManagerTests.java
> +        ProteinSequence proteinFromFile = gbManager.readFromFile(tmpPath);
это тест, который читает url, пишет в файл и потом читает из файла. В принципе, хороший тест, показывающий, что при чтении и записи важные поля не теряются. Но как тест для метода write он не очень удачный, так как используется 2 других метода. Юнит тесты предельно короткие - у нас должен быть объект, который мы пишем в файл и потом смотрим на содержимое файла. В таком случае если read методы сломаются, тест на запись не будет падать. Цель теста - понять, что перестало работать, поэтому в нем должно использоваться по-минимуму зависимостей на другие методы

2022-04-25 12:18 UTC, darina-ovis commented on src/test/java/com/plasmidEditor/sputnik/GenbankManagerTests.java
> +        DNASequence dnaSequence = gbManager.readByURL("X81322");
с чтением из сети в тестах бывают проблемы, связанные с отсутствием интернета или тем, что данные изменились. Чтобы таких проблем не было, обычно используют моки - т.е. делают прокси объект, который возвращает всегда один и тот же детерминированные объект. Вы можете оставить как есть, просто помните об этом

2022-04-25 12:31 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReaderUtils.java
> +        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
Это к тому что try (BufferedReader br = new BufferedReader(new FileReader(path))) что такой вариант предпочтительней, но у тебя по разным классам все поразному, поэтому и написал, что лучше в одном стиле писать

2022-04-25 12:32 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/GenbankManager.java
> +    public T readByURL(@NonNull String accession);
слово public  не требуется)

2022-04-26 12:55 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReadGenbankFileException.java
> +    public String getPath() {
Это нормально , но можно использовать @Getter lombok

2022-04-26 12:56 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReadGenbankUrlException.java
> +        super("Unable to get Genbank file with accession " + accession + " by URL", e);
Обычно тело сообщения выносят в переменную, а для значений исполдьзуют String.format посмотри в эту сторону

2022-04-26 12:59 UTC, iporsh commented on src/test/java/com/plasmidEditor/sputnik/GenbankManagerTests.java
> +            fail(e);
падеение вообще для этого теста может быть корректным кейсом? 
если нет тогда можно все проще сделать одной анатацией @SneakyThrows
попровь плиз во всех местах

2022-04-27 09:27 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/FileDNAGenbankManager.java
> +    private static DNASequence getOnlySequenceFromMap(Map<String, DNASequence> dnaSequences) {
а почему статик?

2022-04-27 09:29 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/FileDNAGenbankManager.java
> +            throw new IllegalArgumentException("Can't read sequence from file");
просто про красоту)
`        if (dnaSequences.size() == 1) {
            return dnaSequences.values().iterator().next();
        } else {
            throw new IllegalArgumentException("Can't read sequence from file");
        }`
лучше когда вот так
`        if (dnaSequences.size() == 1) {
            return dnaSequences.values().iterator().next();
        }
        throw new IllegalArgumentException("Can't read sequence from file");

2022-04-27 11:00 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReadGenbankUrlException.java
> +@Getter(AccessLevel.PUBLIC)
`@Getter(AccessLevel.PUBLIC)`

можно просто @Getter

2022-04-27 11:01 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/utils/ReaderUtils.java
> +            throw new RuntimeException(e.getMessage());
RuntimeException - это нечитаемая ошибка! попробуй создать свою отдельную ошибку

2022-04-27 11:03 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/UrlProteinGenbankManager.java
> +        throw new UnsupportedOperationException("Can't write to URL");
можешь сделать отдельную ошибку
можно все отдельные ошибки положить в отдельную папку exceptions

2022-04-27 12:34 UTC, darina-ovis approved these changes

2022-04-27 12:34 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/exceptions/WriteGenbankFileException.java
> +public class WriteGenbankFileException extends IOException {
Если делать наследование от unckecked ошибки (например RuntimeException), то не нужно объявлять в методе, что он бросает ее. Желательно отдавать предподчтение именно unchecked, так как таскать по всем методам try/catch или throws никому не хочется

2022-04-27 12:34 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/exceptions/WriteGenbankFileException.java
> +    public WriteGenbankFileException(String path, Throwable e) {
Какая причина иметь здесь Throwable? Вы же даже в методах ловите Exception

2022-04-27 12:38 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/exceptions/FileReadingException.java
> +    public FileReadingException(String path, Throwable e) {
Throwable e это оооочень странный способ

2022-04-28 08:12 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/FileDNAGenbankManager.java
> +        throw new IllegalArgumentException("Can't read sequence from file");
Можно и этот эксепшен сделать)

2022-04-28 08:20 UTC, merged