Ability to read and write GenBank files
Bioinformatics-internship-EPAM/plasmidEditor pull request #6
Opened 2022-04-23 18:19 UTC by ShapovalovaIrina

2022-04-25 10:48 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankWriter.java
> +    public void writeToFile(ArrayList<T> sequences, String filename);
ArrayList это реализация, укажи интерфейс

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankReader.java
> +    public ArrayList<T> readFromFile(String filename);
ArrayList это реализация, укажи интерфейс

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinWriter.java
> +        } catch (FileNotFoundException e) {
мне кажется лучше всего сделать свою собственную ошибку для  таких кейсов

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinReader.java
> +            e.printStackTrace();
зачем мне этот стектрейс?

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinReader.java
> +            e.printStackTrace();
что делать с этим в программе?

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinReader.java
> +                    "/tmp",
не понятна строка для чего она нужна, и почему это не константа

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +            e.printStackTrace();
я думаю тебе стоит над стратегией ошибок, т.к. в текущем виде это невозможно использовать в программе, т.е. это тупо забьет консоль и все

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +                            "/tmp",
странное место, почитай ниже об этом же

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +            e.printStackTrace();
читай выше или ниже)

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAWriter.java
> +            e.printStackTrace();
читай выше или ниже

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAWriter.java
> +    public void writeToFile(ArrayList<DNASequence> dnaSequences, String filename) {
ArrayList это реализация, а надо интерфейс

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +        try {
для файла можно использовать структуру  try ()

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +        ArrayList<DNASequence> dnaSequencesList = new ArrayList<>();
используй интерфейс

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +        DNASequence dnaSequence = null;
плой вариант
ты могбы использовать  где-то в 31 строчке ретурн

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +    public ArrayList<DNASequence> readFromFile(String filename) {
используй интерфейс

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAWriter.java
> +            try(OutputStream outputStream = new FileOutputStream(filename)) {
старайся пользоваться однотипными решениями, у тебя где-то так, где-то тоже самое делается одинаково

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinReader.java
> +        ProteinSequence proteinSequence = null;
плохой вариант, смотри выше я описал почему

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinReader.java
> +        ArrayList<ProteinSequence> proteinSequencesList = new ArrayList<>();
используй интерфейс

2022-04-25 10:58 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinReader.java
> +    public ArrayList<ProteinSequence> readFromFile(String filename) {
используй интерфейс

2022-04-25 11:21 UTC, darina-ovis requested changes
Тут не хватает обязательных полей, описанных в задаче. Как только понадобится их добавить, все интерфейсы изменяться, потому что работа пойдет не со списками последовательностей, но объектами, содержащими эти списки. Лучше с самого начала иметь объект со списком внутри и прочими обязательными для формата полями. И посмотрите на обработку исключений - проглатывать ошибки в приложении в высшей степени неправильно.

2022-04-25 11:21 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +            e.printStackTrace();
В случае ошибки будет очень сложно понять, что произошло. Ошибку нужно писать в log файл, а не в консоль. Здесь при ошибке чтения возвращается null, как будто это нормальный случай. Но это не так. Возвращая тут null, пользователи этого метода никогда не пойдут причину ошибки и должны будут как-то обработать null - по крайней мере сделать проверку. Когда поведение системы неправильное, нужно бросать exception - именно для этого они и созданы. Перебросьте unckecked exception либо свой собственный либо стандартный runtime exception.

2022-04-25 11:21 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAReader.java
> +        }
не очень принято ловить Exception. Это называется pockemon error handling. Ловить лучше те ошибки, которые вы ожидаете и обрабатывать их по-разному. Ошибки должны быть понятны - это сильно упрощает поиск проблем в будущем

2022-04-25 11:21 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAWriter.java
> +            e.printStackTrace();
лучше писать в log файл. Тут хорошо, что ошибки обрабатываются по-разному. Не уверена насчет Exception. Не бойтесь выбрасывать ошибки, когда поведение системы неправильное

2022-04-25 11:21 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinReader.java
> +        }
в случае ошибки вернется пустой список и понять, почему он пустой, будет невозможно. Хотя пустой список лучше, чем null)

2022-04-25 11:21 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankReader.java
> +    public ArrayList<T> readFromFile(String filename);
Такой интерфейс выглядит немного проблемным. С точки зрения логики нам не важно, читаем мы из файла локально или удаленно - это детали реализации. У вас даже выходной формат отличается - это потом может привести к проблемам с работой по чтению. Придется делать if/else на то, откуда мы читаем и код будет отличаться, хотя логика одинаковая. Было бы лучше использовать один интерфейс и 2 его реализации для чтения локально и удаленно. Посмотрите на паттерн стратегия

2022-04-25 11:21 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankProteinWriter.java
> +            e.printStackTrace();
тоже самое, что в reader-е: пишем в логи, критические ошибки не глотаем, а бросаем

2022-04-25 11:21 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankDNAWriter.java
> +            }
Файл, который создается, не будет полноценным файлом genbank формата. Тут не хватает обязательных полей.

2022-04-26 09:03 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/protein/GenBankProteinFileReader.java
> +}
Это зачем?

2022-04-26 09:03 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/protein/GenBankProteinUrlReader.java
> +}
Это зачем?

2022-04-26 09:03 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/dna/GenBankDNAWriter.java
> +            e.printStackTrace();
Лучше писать в лог файл. Критические ошибки не стоит проглатывать

2022-04-26 09:03 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankWriter.java
> +    public void writeToFile(ArrayList<T> sequences, String filename);
```suggestion
    public void writeToFile(List<T> sequences, String filename);
```

2022-04-26 09:03 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/genbank/io/GenBankReader.java
> +    public ArrayList<T> readFromFile(String filename);
```suggestion
    public List<T> readFromFile(String filename);
```

2022-04-26 09:22 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/genbank/io/protein/GenBankProteinFileReader.java
> +}
Извиняюсь, вчера почему-то закоммитились не все изменения

2022-04-26 13:24 UTC, merged