Sputnik upload
Bioinformatics-internship-EPAM/plasmidEditor pull request #8
Opened 2022-05-09 14:21 UTC by Pelevina

2022-05-11 11:23 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@PostMapping(path="/genbank/dna", produces=MediaType.APPLICATION_JSON_VALUE)
/genbank  можно использовать  для всей группы этотих контроллеров

2022-05-11 11:24 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			dnaFileUploadService.upload(file);
MultipartFile это кастомное решение, не хорошо его пробрасывать дальше , лучше в твоем случае использовать InputStream

2022-05-11 11:25 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			return ResponseEntity.badRequest().body("File wasn't uploaded because " + e.getMessage());
А какой статус ответа будет приходить?

2022-05-11 11:25 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +	public void upload(MultipartFile file) {
MultipartFile это кастомное решение, не хорошо его пробрасывать дальше , лучше в твоем случае использовать InputStream

2022-05-11 11:25 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +	public void upload(MultipartFile file);
MultipartFile это кастомное решение, не хорошо его пробрасывать дальше , лучше в твоем случае использовать InputStream

2022-05-11 14:43 UTC, darina-ovis requested changes

2022-05-11 14:43 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			return ResponseEntity.badRequest().body("File wasn't uploaded because " + e.getMessage());
объявлено, что метод возвращает json, но возвращаемая строка - это не json объект. Часто для методов на создание объектов используется статус 201 created и при этом пустое тело ответа. В случае ошибки может прийти статус 400 и json объект. Например, {"error":"failed to upload....", "reason": "some reason"} В вашем случае ошибка тоже вернется строкой. Посмотрите в сторону аннотации ResponseBody https://www.baeldung.com/spring-request-response-body

2022-05-11 14:43 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +		// TODO Auto-generated method stub
уберите плз мусорный код

2022-05-11 14:43 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +
с этим интерфейсом явно что-то не то. Это у вас сервис или контроллер?

2022-05-11 14:43 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +
Назначение этих методов мне не понятно. Даже если допустить, что вы хотели написать контроллер для получения файлов, то зачем вам модель? К тому же, экспорт файлов - это отдельная задача и должна быть в отдельном пулл реквесте

2022-05-11 14:43 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +	}
хорошее решение для обработки ошибок, только этому методу место в контроллере, т.е. **классу** с аннотацией **RestController** (или Controller)

2022-05-11 14:43 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +}
Вот это больше похоже на интерфейс, чем interface FileUploadService<T>

2022-05-11 14:43 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +		SpringApplication.run(UploadingFilesApplication.class, args);
Не понимаю, что вы пытаетесь тут сделать. У нас должно быть одно Spring приложение. Нам нужен класс с аннотацией RestController с точками входа (методы аннотированные PostMapping, GetMapping и т.д.) и из этих методов вызываются методы сервиса, где сервис выполняет непостредственно логику. Например, загрузку файла, проверку файла, сохранение в базу данных и прочее.

2022-05-11 14:43 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +	}
Что за storageService?

2022-05-11 18:04 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +		// TODO Auto-generated method stub
Убрано лишнее

2022-05-11 18:05 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +
Сейчас этого нет

2022-05-11 18:05 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +
Сейчас этого нет

2022-05-11 18:05 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +	}
Сейчас этого нет в этом файле

2022-05-11 18:06 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +}
Сейчас этого нет

2022-05-11 18:06 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +		SpringApplication.run(UploadingFilesApplication.class, args);
Сейчас этого нет

2022-05-11 18:06 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +	}
Сейчас этого нет

2022-05-11 18:22 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			dnaFileUploadService.upload(file);
Где оставить MultipartFile, а где заменить его на InputStream?

2022-05-11 19:50 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@PostMapping(path="/genbank/dna", produces=MediaType.APPLICATION_JSON_VALUE)
То есть получается можно использовать только ProteinFileUploadService?

2022-05-11 19:51 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			return ResponseEntity.badRequest().body("File wasn't uploaded because " + e.getMessage());
В нормальном случае должен приходить 200, в случае ошибки - 400.

2022-05-12 07:31 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +	}
ExceptionHandler теперь в контроллере

2022-05-12 07:43 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			dnaFileUploadService.upload(file);
Везде MultipartFile заменено на InputStream

2022-05-12 07:43 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +	public void upload(MultipartFile file) {
Везде MultipartFile заменено на InputStream

2022-05-12 07:43 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +	public void upload(MultipartFile file);
Везде MultipartFile заменено на InputStream

2022-05-12 10:23 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@PostMapping(path="/genbank/dna", produces=MediaType.APPLICATION_JSON_VALUE)
нет))) 
`@Controller
@RequestMapping(value = **"genbank"**)
public class FileEditorController {`

2022-05-12 14:49 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			return ResponseEntity.badRequest().body("File wasn't uploaded because " + e.getMessage());
Сделан внутренний класс, который должен преобразовать ответ в json.

2022-05-12 14:50 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@PostMapping(path="/genbank/dna", produces=MediaType.APPLICATION_JSON_VALUE)
@RequestMapping(value = "/genbank") теперь стоит перед классом контроллера

2022-05-12 15:40 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@PostMapping(path="/genbank/dna", produces=MediaType.APPLICATION_JSON_VALUE)
теперь путь будет выглядеть как /genbank/genbank/dna

2022-05-12 15:40 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	}
Вам не нужно возвращать ошибку при успешном выполнении метода. Не должно быть тут ResponseEntity<JsonError>
Для статуса можно использовать аннтотацию ResponseStatus

2022-05-12 15:40 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +
Даже если бд не готова, вы можете сделать интерфейс для dao с пустыми методами либо с сохранением файла на диск (возможная реализация). Уровень же сервиса можно написать

2022-05-12 17:39 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	}
Использована ResponseStatus перед контроллером. Лишний /genbank убран

2022-05-16 11:07 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@ExceptionHandler(Exception.class)
Лучше вынести отдельно это , а то при появлении новых котроллеров, это часть не будет работать

2022-05-16 11:07 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +	@Override
код стайл(

2022-05-16 11:08 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +            System.out.println("Upload " + accession + "." + version);
в консоль кидать ничего не стоит
стоит использовать лог

2022-05-16 11:09 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +                throw new Exception("Upload " +
Лучше иметь кастомную ошибку

2022-05-16 11:10 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +    private void validateListSize(List<ProteinSequence> sequences) throws Exception {
можем мы вынести это в отдельный класс т.к. код задублирован (точно также есть как минимум в DNAFileUploadService )

2022-05-16 11:33 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +            System.out.println("Upload " + accession + "." + version);
В консоль в этом файле уже больше не кидает. Сохраняет в базу данных

2022-05-16 11:34 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@ExceptionHandler(Exception.class)
То есть в новый класс?

2022-05-16 11:34 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +	@Override
А что за замечания по код стайлу?

2022-05-16 11:35 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +                throw new Exception("Upload " +
Что такое кастомная ошибка?

2022-05-16 12:04 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +    private void validateListSize(List<ProteinSequence> sequences) throws Exception {
Проверка размеров находится на стороне ридера

2022-05-16 12:08 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +
Есть логика

2022-05-16 13:00 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +                throw new Exception("Upload " +
значит, Exception, который вы написали сами, а не один из java пакетов

2022-05-16 13:06 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +                throw new Exception("Upload " +
Валидация находится на стороне ридера и использует пользовательское исключение

2022-05-16 13:13 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@ExceptionHandler(Exception.class)
Если вы объявляете ExceptionHandler в контроллере, он действует только для этого класса. Если выносите в класс с аннотацией ControllerAdvice, то такой exception handler работает для всех контроллеров, где нет своих exception handler-ов

2022-05-16 13:13 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +				throw new NullPointerException();
Не думаю, что это хорошая идея кинуть тут NPE. Вы ее поймаете в 40 строчке и выведете пустое сообщение.

2022-05-16 13:13 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +
Я бы хотела видеть тут логику, одинаковую и для сохранения в бд и на диск. То, что написано в этом методе, должно быть в одной из реализаций dao, в другой реализации dao будет сохранение в бд, но логика сервиса для них не отличается. Сервис подготавливает данные для сохранения (например, создает объект из 3 полей, проверяет, что файл корректный и все такое) и просто отдает данные дао.

2022-05-16 13:13 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +        	}
постарайтесь избавиться от дубликатов кода. Сейчас этот код очень похож на DNAFileUploadService. И пишется sequen**C**e - грамматика очень важна для кода. Потому что когда проект большой, программисты часто ищут что-то по какому-нибудь слову. Если слово написано с ошибкой, то это место могут не найти и это может быть причиной ошибки в будущем. Обычно идея подсвечивает такие слова

2022-05-16 13:15 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +	@Override
отступ съехал

2022-05-16 13:49 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +	@Override
Выровнялось

2022-05-16 14:28 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			dnaFileUploadService.upload(file);
на вход контролера должен быть MultipartFile
на вход сервисов InputStream

2022-05-16 14:29 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +				throw new NullPointerException();
Чем тогда лучше заменить эту инструкцию в 38 строке? Ведь нужно, чтобы если sequence является nullом, то выходило исключение.

2022-05-16 14:29 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +        	}
Sequence исправлено.

2022-05-16 14:33 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +
Сервисы сохраняют только в бд. В обоих сервисах одинаковая логика. Переделать один из них на сохранение на диск?
Использовать один класс-наследник от AbstractSequence, чтобы избавится от дубликатов кода?

2022-05-16 14:36 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@ExceptionHandler(Exception.class)
А если нужно своё сообщение для каждого контроллера, что тогда делать?

2022-05-16 14:53 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +			dnaFileUploadService.upload(file);
Теперь на входе контроллера MultipartFile, а на входе сервисов InputStream

2022-05-16 17:30 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +
https://itanddigital.ru/webapplications посмотрите раздел "Уровни архитектуры веб-приложений". Работа с бд и файловой системой - это уровень доступа к данным. На уровне сервиса у нас есть некий интерфейс, который может дать нам объект с файлом, accession и version. Откуда он объект берется - из файловой системы или из бд, сервис не интересует. 

Насчет дубликтов. Вы можете использовать паттерн Template, например.

2022-05-16 17:32 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@ExceptionHandler(Exception.class)
Если в controller-е есть свой exception handler, он используется вместо controller advice

2022-05-16 17:37 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +                throw new Exception("Upload " +
Не очень поняла ваш коммент. Exception - это слишком общее понятие. Всегда лучше быть более конкретным. Даже если вы не хотите создавать свой Exception, лучше бросать что-то более менее специфичное, например IllegalArgumentException
https://programming.guide/java/list-of-java-exceptions.html вот полный список - посмотрите что лучше по смыслу вам подходит. Или создайте что-то свое

2022-05-16 17:50 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +				throw new NullPointerException();
Если что-то не должно быть null, нужно проверить, что оно не null, а если null, то выдать осмысленное сообщение. В вашем коде объект даже не null, он экземпляр другого класса. NPE как-то совсем не про это. 

Вот например в библиотеке guava есть такие методы 

https://guava.dev/releases/20.0/api/docs/src-html/com/google/common/base/Preconditions.html#line.120

```
public static void checkArgument(boolean expression, @Nullable Object errorMessage) {
    if (!expression) {
      throw new IllegalArgumentException(String.valueOf(errorMessage));
    }
  }
```

вызывается он так `Preconditions.checkArgument(sequence instanceof DNASequence, "DNASequence is expected")`

Вам не нужно использовать тут guava. Это просто пример

2022-05-16 17:50 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +                throw new Exception("Upload " +
Я имела ввиду, что теперь используется более специфичное исключение, чем Exception

2022-05-16 17:52 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +        	}
Исправьте во всех местах) Когда код пишут методом copy/paste, очень часто забывают про все места - тем и страшны дубликаты кода

2022-05-16 20:19 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +	@ExceptionHandler(Exception.class)
Создан класс с аннотацией ControllerAdvice

2022-05-16 20:20 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +				throw new NullPointerException();
Изменён тип исключения. Добавлено событие

2022-05-16 20:21 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +        	}
Дубликаты удалены

2022-05-16 21:09 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/exceptions/FileUploadException.java
> +public class FileUploadException extends Exception {
А почему Exception ?

2022-05-16 21:09 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/controllers/JsonError.java
> +public class JsonError {
странное название

2022-05-16 21:11 UTC, iporsh commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadServiceUtils.java
> +		File file = File.createTempFile("dna", ".tmp");
почему именно эти рассширения?
Можем мы их вынести в настройку?

2022-05-16 21:21 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/exceptions/FileUploadException.java
> +public class FileUploadException extends Exception {
Exception - базовый класс для всех видов exception. Какой класс лучше всего подойдёт в качестве родителя FileUploadException?

2022-05-16 21:22 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/JsonError.java
> +public class JsonError {
В чём его странность? Как лучше переименовать этот класс?

2022-05-16 21:24 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadServiceUtils.java
> +		File file = File.createTempFile("dna", ".tmp");
Расширение AbstractSequence, потому что тип T должен быть наследником класса AbstractSequence.

2022-05-17 05:51 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/DNAFileUploadService.java
> +
Дубликаты удалены. Сохранение в бд сделать в отдельном методе или оставить в методе upload? Сервисы сделаны так, что работают с файлом из любого места, и дают accession и version

2022-05-17 05:52 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/exceptions/FileUploadException.java
> +public class FileUploadException extends Exception {
Переделано на RuntimeException

2022-05-17 05:53 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/controllers/JsonError.java
> +public class JsonError {
Переименовано в ErrorResponseBody

2022-05-17 15:34 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +	private final GenBankServiceImpl genBankServiceImpl;
это должен быть интерфейс уровня дао

2022-05-18 08:52 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadServiceUtils.java
> +		File file = File.createTempFile("dna", ".tmp");
Создания временного файла больше нет.

2022-05-18 09:03 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +	private final GenBankServiceImpl genBankServiceImpl;
А это есть реализация интерфейса уровня дао

2022-05-20 18:18 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadServiceUtils.java
> +	public void saveSequenceToDB(T sequence, InputStream inputStream, GenBankServiceImpl genBankServiceImpl) throws IllegalArgumentException,
Это выглядит странно. У вас всего один GenBankServiceImpl - зачем его передавать параметром? Классы типа Utils обычно содержат статические методы. Многие программисты складывают туда все, что не знают куда положить. Это плохая практика. Разберитесь со структурой. Если вам приходится передавать в метод ссылку на объект только потому, что этот объект бин, значит, что-то пошло не так.

2022-05-20 18:20 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +	private final GenBankServiceImpl genBankServiceImpl;
```suggestion
	private final GenBankService genBankService;
```

2022-05-20 18:22 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/controllers/FileUploadController.java
> +		return ResponseEntity.badRequest().body(new ErrorResponseBody("failed to upload genbank file", e.getMessage()));
при таком подходе в лог никогда не попадет stacktrace и будут чистые логи, и только пользователи будут видеть ошибку.
Можете не исправлять в данном случае, просто помните, что выводить в логи ошибки очень важно в боевых проектах.

2022-05-20 18:56 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadServiceUtils.java
> +	public void saveSequenceToDB(T sequence, InputStream inputStream, GenBankServiceImpl genBankServiceImpl) throws IllegalArgumentException,
Те методы класса GenBankServiceImpl, что я применяла, не статические и написаны другими ребятами. Нужно добавить модификатор static в эти методы?

2022-05-20 19:01 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/ProteinFileUploadService.java
> +	private final GenBankServiceImpl genBankServiceImpl;
Изменила с GenBankServiceImpl на GenBankService

2022-05-21 11:55 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadServiceUtils.java
> +	public void saveSequenceToDB(T sequence, InputStream inputStream, GenBankServiceImpl genBankServiceImpl) throws IllegalArgumentException,
Теперь есть абстрактный класс вместо интерфейса и утильного класса

2022-05-24 12:10 UTC, darina-ovis commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +        GenBankServiceImpl genBankServiceImpl = new GenBankServiceImpl();
Это Spring bean  - его не надо создавать, его надо inject-тить, т.е. должно быть так
```
        @Autowired
        GenBankService genBankService;
        
        protected void void saveSequenceToDB(T sequence, InputStream inputStream) throws IllegalArgumentException, IOException, GenBankNotFoundException, RepeatFileUploadingException {
        ...
        if(genBankService.is...)
   
```

Обратите внимание, что лучше объявлять его как interface, не конкретный класс. Spring сам разберется и найдет подходящую реализацию интерфейса (в вашем случае она одна)

2022-05-24 14:15 UTC, Pelevina commented on src/main/java/com/plasmidEditor/sputnik/uploadServices/FileUploadService.java
> +        GenBankServiceImpl genBankServiceImpl = new GenBankServiceImpl();
Добавлено Autowired поле типа GenBankService и используется интерфейс.

2022-05-26 15:35 UTC, darina-ovis approved these changes

2022-05-26 15:35 UTC, merged