Upload genbank files endpoint
Bioinformatics-internship-EPAM/plasmidEditor pull request #9
Opened 2022-05-10 12:58 UTC by ShapovalovaIrina

2022-05-10 13:07 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +        );
Не уверена насчет этого тестового кейса, так как фактически DNA файл считывается и с помощью ProteinReader (тест падает). Видимо дело в том, что символы последовательности белка включают в себя символы ДНК?

Будет ли достаточным условием валидации проверка на то, что последовательность содержит не только символы ACGT, но и другие, специфичные только для белка? Может быть есть какие-нибудь другие признаки, по которым можно отличить типы файлов?

2022-05-11 11:13 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            return ResponseEntity.badRequest().body("Upload file unexpected error. Reason: " + e.getMessage());
тут правильней тогда другой тип статуса ответ(в твоем случае  сейчас это будет 200 и когда хорошо и когда плохо)

2022-05-11 11:14 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            path="/genbank/dna",
/genbank можно вынести для всей групапы этих запросов

2022-05-11 11:16 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +//                 genBankService.upload(accession, version, new String(multipartFile.getBytes()));
этот код уже выглядит странно )

2022-05-11 11:17 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +        for (DNASequence sequence : sequenceList) {
из хороших практик - это разделять код на различные методы, в текущем методе простыня, которую можно порезать по функцтоналу на различные методы

2022-05-11 11:17 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +                throw new Exception("Upload " +
Лучше тоже кастомную ошибку

2022-05-11 11:18 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +        switch (sequences.size()) {
sequences может быть null?

2022-05-11 11:19 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +    private void validateListSize(List<DNASequence> sequences) throws Exception {
throws Exception  какой смысл в этом?

2022-05-11 11:20 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/FileEditorService.java
> +    void uploadFile(MultipartFile file) throws FileEditorUploadException;
отлично что используешь интерфейсы!! но MultipartFile  это совсем не универсально , требуется использовать общие интерфейсы - реализации , в твоем случае лучше если это будет InputStream

2022-05-11 11:21 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/ProteinFileEditorService.java
> +    private void validateListSize(List<ProteinSequence> sequences) throws Exception {
код дублируется, может его вынести в отдельный класс?

2022-05-11 11:22 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +    private MultipartFile getMultipartFile(String content) {
ты для это можешь использовать MVC tests

2022-05-11 14:15 UTC, darina-ovis requested changes

2022-05-11 14:15 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            return ResponseEntity.ok("Successfully upload file");
объявлено, что метод возвращает json, но возвращаемая строка - это не json объект. Часто для методов на создание объектов используется статус 201 created и при этом пустое тело ответа. В случае ошибки может прийти статус 400 и json объект. Например, {"error":"failed to upload....", "reason": "some reason"} В вашем случае ошибка тоже вернется строкой. Посмотрите в сторону аннотации ResponseBody https://www.baeldung.com/spring-request-response-body

2022-05-11 14:15 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            return ResponseEntity.badRequest().body("Upload file unexpected error. Reason: " + e.getMessage());
Чтобы не дублировать код в двух методах по обработке ошибок, можно использовать метод, аннотированный exceptionHandler Посмотрите пример тут 
https://www.baeldung.com/exception-handling-for-rest-with-spring

2022-05-11 14:15 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +            System.out.println("Upload " + accession + "." + version);
используйте логгер пожалуйста

2022-05-11 14:15 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/service/ProteinFileEditorService.java
> +            sequenceList = new GenBankProteinFileReader().read_sequence(file.getAbsolutePath());
принято переменные и методы называть в camelCase формате. Переименуйте плз read_sequence

2022-05-11 14:15 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/service/ProteinFileEditorService.java
> +            System.out.println("Upload " + accession + "." + version);
используйте логгер

2022-05-11 14:15 UTC, darina-ovis commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +        fileEditorService.uploadFile(multipartFile);
не хватает части проверки. Нет ни одного assert. Если тест проверяет, что не брошено exception-ов, то обычно пишут try-catch и в catch пишут assertFalse - так сразу понятно, что тест проверяет. Задача теста быть максимально простым с точки зрения понимания, что он проверяет. Так же для тестов важно имя. Этот тест я бы назвала как-нибудь в духе testDnaFileUploadSuccessfully. Не бойтесь длинных названий методов в тестах

2022-05-11 14:15 UTC, darina-ovis commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +        MultipartFile multipartFile = getMultipartFile(input, file.getName());
Старайтесь избегать дубликатов кода даже в тестах. Это поможет сократить время разработки и рефакторинга в будущем. Вынесите эти строчки с параметром в отдельный метод

2022-05-11 14:15 UTC, darina-ovis commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +        );
Вполне справедливо падает. Вам нужен файл не с ДНК, а файл, содержащий буквы не из алфавита белков https://biojava.org/wiki/BioJava:Cookbook:Alphabets
Насчет проверки "содержит не только символы ACGT, но и другие, специфичные только для белка" - это неверно. Файл с белками может быть вполне правильным, имея только 4 буквы альфавита - нет такого правила, что должен иметь все буквы из альфавита.

2022-05-11 19:35 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            return ResponseEntity.badRequest().body("Upload file unexpected error. Reason: " + e.getMessage());
Но разве функция badRequest не устанавливает код 400?

2022-05-14 08:11 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            path="/genbank/dna",
Вынесла пути в отдельный файл с конфигурацией для API

2022-05-14 08:12 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +        for (DNASequence sequence : sequenceList) {
Вынесла в отдельный метод

2022-05-14 08:13 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +        switch (sequences.size()) {
Добавила @NonNull аннотацию

2022-05-14 08:13 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/FileEditorService.java
> +    void uploadFile(MultipartFile file) throws FileEditorUploadException;
Переделала на InputStream

2022-05-14 08:13 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/ProteinFileEditorService.java
> +    private void validateListSize(List<ProteinSequence> sequences) throws Exception {
Вынесла в отдельный класс FileEditorServiceUtils

2022-05-14 08:15 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +    private MultipartFile getMultipartFile(String content) {
Немного не поняла комментарий.   
Сейчас вспомогательные функции переписаны таким образом:

```java
    private FileInputStream getInputStreamFromFile(String filename) throws FileNotFoundException {
        return new FileInputStream(new File(filename));
    }

    private InputStream getInputStreamFromContent(String content) {
        return new ByteArrayInputStream(content.getBytes());
    }
```

2022-05-14 08:16 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            return ResponseEntity.ok("Successfully upload file");
Вынесла обработку исключений в отдельный общий handler - ControllersExceptionHandler. Использую аннотации \@ControllerAdvice и \@ExceptionHandler

2022-05-14 08:17 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            return ResponseEntity.badRequest().body("Upload file unexpected error. Reason: " + e.getMessage());
Готово (комментарий выше)

2022-05-14 08:17 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +            System.out.println("Upload " + accession + "." + version);
Готово

2022-05-14 08:17 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/ProteinFileEditorService.java
> +            sequenceList = new GenBankProteinFileReader().read_sequence(file.getAbsolutePath());
Переименовала

2022-05-14 08:17 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/ProteinFileEditorService.java
> +            System.out.println("Upload " + accession + "." + version);
Готово

2022-05-14 08:17 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +        MultipartFile multipartFile = getMultipartFile(input, file.getName());
Готово

2022-05-14 14:51 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +        );
Добавила тесты на загрузку файлов ДНК и белка, где в последовательности есть буквы не из алфавита

2022-05-14 14:51 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +                throw new Exception("Upload " +
Вынесла в отдельную ошибку валидации

2022-05-14 14:52 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +    private void validateListSize(List<DNASequence> sequences) throws Exception {
Переделала на `throws SequenceValidationException`

2022-05-14 14:53 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/FileEditorServiceTest.java
> +        fileEditorService.uploadFile(multipartFile);
Добавила `assertDoesNotThrow` и переименовала тесты)

2022-05-16 10:33 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +@Controller
`@Controller
@RequestMapping(value = EDIT_FILE_PATH)`

2022-05-16 10:34 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +@Controller
так будет лучше

2022-05-16 10:35 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/FileEditorServiceUtils.java
> +        File file = File.createTempFile("sequence", ".tmp");
а как мы потом временный файл удаляем?

2022-05-16 10:37 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/io/protein/GenBankProteinFileReader.java
> +    public List<ProteinSequence> readSequence(@NonNull String filename) throws GenBankFileReaderException {
e.printStackTrace() совсем не нужен, посмотри плиз везьде и удали

2022-05-16 20:53 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/genbank/io/protein/GenBankProteinFileReader.java
> +    public List<ProteinSequence> readSequence(@NonNull String filename) throws GenBankFileReaderException {
Удалила

2022-05-16 20:56 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/FileEditorServiceUtils.java
> +        File file = File.createTempFile("sequence", ".tmp");
Вообще там на файл вешалось действие, чтобы при завершении ВМ он удалялся - `file.deleteOnExit();`. Но кажется, что завершение ВМ в серверном процессе действие не очень быстрое...

Добавила поэтому в блок try/catch, где мы пишем в файл, блок finally с удалением файла.
```java
        } finally {
            if (file != null && !file.delete())
                log.error("Failed to delete tmp file " + file.getName());
        }
```

2022-05-16 20:57 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +@Controller
Переделала :)

2022-05-16 20:57 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +//                 genBankService.upload(accession, version, new String(multipartFile.getBytes()));
Переделала немного. Сделала пока что полноценную заглушку для репозитория

2022-05-16 21:03 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/genbank/repository/domains/GenBankEntity.java
> +        schema = "genbank",
это тоже лучше вынести в константу

2022-05-16 21:05 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +        File file = null;
любой код анализатор на это будет ругаться

2022-05-16 21:05 UTC, iporsh commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +        String content;
и на это)

2022-05-16 21:06 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/genbank/repository/domains/GenBankEntity.java
> +        schema = "genbank",
А этот класс потом подтянется из пул реквеста с БД. Возможно там эта переменная будет уже в константе. 

Если нет, то вынесу.

2022-05-17 09:06 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileEditorService.java
> +        File file = null;
А можете, пожалуйста, уточнить почему?..

2022-05-24 13:31 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +                .build();
если использовать аннотацию responseStatus, то метод возвращает void. Читаться будет лучше

2022-05-24 13:31 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/exceptions/FileAlreadyExistsException.java
> +public class FileAlreadyExistsException extends Exception {
лучше наследоваться от RuntimeException, тогда не нужно этот тип ошибки таскать по всем методах

2022-05-24 13:31 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/exceptions/FileUploadException.java
> +public class FileUploadException extends Exception {
и здесь тоже самое. Перечисление простыни throws в объявлении методов мешает читабельности

2022-05-24 13:31 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            FileAlreadyExistsException
лучше свои exception-ы сделать unckecked. Тогда не нужно писать этот длинный список в каждом методе

2022-05-24 13:31 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/service/FileUploadService.java
> +    void uploadFile(InputStream file) throws FileUploadException, SequenceValidationException, FileAlreadyExistsException;
зачем интерфейсу быть spring bean-ом?

2022-05-24 13:31 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileUploadService.java
> +        FileUploadServiceUtils<DNASequence> serviceUtils = new FileUploadServiceUtils<>();
FileUploadServiceUtils объявлен Spring bean-ом. Зачем его создавать с помощью new?
Если это бин, его надо inject-тить с помощью Autowired и я лучше его переименовать.

Вообще, обычно классы с постфиксом Utils  не делают бинами. В них содержится логика, которую можно использовать много где. Обычно эти классы содержат статические методы - вот пример классического утильного класса https://commons.apache.org/proper/commons-math/javadocs/api-2.2/org/apache/commons/math/util/MathUtils.html

2022-05-24 13:31 UTC, darina-ovis commented on src/test/java/com/plasmideditor/rocket/service/FileUploadServiceTest.java
> +    }
не понимаю, зачем выполнять это перед каждым тестом

2022-05-25 20:11 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/service/FileUploadServiceTest.java
> +    }
Переместила в метод с аннотацией @BeforeAll

2022-05-25 20:11 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/DNAFileUploadService.java
> +        FileUploadServiceUtils<DNASequence> serviceUtils = new FileUploadServiceUtils<>();
Убрала @Service и сделала методы статическими

2022-05-25 20:12 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/FileUploadService.java
> +    void uploadFile(InputStream file) throws FileUploadException, SequenceValidationException, FileAlreadyExistsException;
Убрала

2022-05-25 20:12 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +            FileAlreadyExistsException
Готово

2022-05-25 20:12 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/exceptions/FileAlreadyExistsException.java
> +public class FileAlreadyExistsException extends Exception {
Готово

2022-05-25 20:12 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/controller/FileUploadController.java
> +                .build();
Переделала

2022-05-25 20:12 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/exceptions/FileUploadException.java
> +public class FileUploadException extends Exception {
Готово

2022-05-26 11:56 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/controller/FileUploadControllerTest.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
ты можешь сделать статическим этот метод

2022-05-26 11:56 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/controller/FileUploadControllerTest.java
> +    public FileUploadControllerTest() throws IOException {
а зачем это?

2022-05-26 11:57 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/controller/FileUploadControllerTest.java
> +    public void testSuccessfullyUploadDNAFile() throws Exception {
throws Exception для чего это в тесте?

2022-05-26 11:58 UTC, iporsh commented on src/test/java/com/plasmideditor/rocket/service/FileUploadServiceTest.java
> +    public void testSuccessfullyUploadProteinFile() throws IOException {
для чего это IOException ?

2022-05-26 15:54 UTC, darina-ovis commented on src/main/java/com/plasmideditor/rocket/web/service/ProteinFileUploadService.java
> +        FileUploadServiceUtils.insertSequence(genBankRepository, accession, version, content);
передавать ссылку на бин - не очень хорошо. Это верный признак того, что что-то пошло не так. Код в insertSequence не похож на утилиту, он похож на логику. Его логичнее перенести на уровень сервиса. либо отдельный сервис для сохранения, либо общий метод для классов-наследников.

2022-05-27 17:07 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/controller/FileUploadControllerTest.java
> +    public void testSuccessfullyUploadDNAFile() throws Exception {
Функция mockMvc.perform бросает Expection видимо в любом случае. Даже в документации спринга в примерах тестирования контроллера через MockMvc пишут таким же образом https://spring.io/guides/gs/testing-web/.

2022-05-27 17:10 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/service/FileUploadServiceTest.java
> +    public void testSuccessfullyUploadProteinFile() throws IOException {
Исправила ошибку с IOException на FileNotFoundException.

Функция в тесте `getInputStreamFromFile` может бросить исключение, если файл не найден.

2022-05-27 17:37 UTC, ShapovalovaIrina commented on src/main/java/com/plasmideditor/rocket/web/service/ProteinFileUploadService.java
> +        FileUploadServiceUtils.insertSequence(genBankRepository, accession, version, content);
Перенесла метод в GenBankService

2022-05-27 17:39 UTC, ShapovalovaIrina commented on src/test/java/com/plasmideditor/rocket/controller/FileUploadControllerTest.java
> +    public FileUploadControllerTest() throws IOException {
Конструктор нужен был для инициализации multipartFile, а там getMultipartFileFromString бросал ошибку. 

Переделала инициализацию файла на функцию с аннотацией @BeforeAll

2022-05-30 12:57 UTC, darina-ovis approved these changes

2022-05-30 12:57 UTC, merged